apiVersion: v1
kind: Pod
metadata:
  name: cluster
spec:
  securityContext:
    runAsUser: 270999
    runAsGroup: 1132
  containers:
    - name: cluster-pod
      image: docker.io/stmorse314/transformers-torch:latest
      resources:
        requests:
          memory: '64Gi'
          cpu: '32'
        limits:
          memory: '64Gi'
          cpu: '32'
      command: ['/bin/sh']
      args:
        - '-c'
        - |
          echo "Running container..."
          cd /sciclone/home/stmorse/projects/reddit/cluster
          python sk_cluster.py > c_out.log
          sleep infinity
      volumeMounts:
        - name: home
          mountPath: /sciclone/home/stmorse
        - name: results
          mountPath: /sciclone/geograd/stmorse
  volumes:
    - name: home
      nfs:
        server: 128.239.56.166
        path: /sciclone/home/stmorse
    - name: results
      nfs:
        server: 128.239.59.144
        path: /sciclone/geograd/stmorse